name: weather_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/weather_logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
